/*
 * Collection Service
 *
 * API for managing collection
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product-list.Model;
using product-list.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product-list.Test.Model
{
    /// <summary>
    ///  Class for testing OrderByDirection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderByDirectionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderByDirection
        //private OrderByDirection instance;

        public OrderByDirectionTests()
        {
            // TODO uncomment below to create an instance of OrderByDirection
            //instance = new OrderByDirection();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderByDirection
        /// </summary>
        [Fact]
        public void OrderByDirectionInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderByDirection
            //Assert.IsType<OrderByDirection>(instance);
        }
    }
}
