/*
 * Collection Service
 *
 * API for managing collection
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product-list.Model;
using product-list.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product-list.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistCreateProductListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistCreateProductListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistCreateProductListResponse
        //private ProductlistCreateProductListResponse instance;

        public ProductlistCreateProductListResponseTests()
        {
            // TODO uncomment below to create an instance of ProductlistCreateProductListResponse
            //instance = new ProductlistCreateProductListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistCreateProductListResponse
        /// </summary>
        [Fact]
        public void ProductlistCreateProductListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistCreateProductListResponse
            //Assert.IsType<ProductlistCreateProductListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'List'
        /// </summary>
        [Fact]
        public void ListTest()
        {
            // TODO unit test for the property 'List'
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
    }
}
