/*
 * Collection Service
 *
 * API for managing collection
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product-list.Model;
using product-list.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product-list.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistSearchProductListsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistSearchProductListsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistSearchProductListsResponse
        //private ProductlistSearchProductListsResponse instance;

        public ProductlistSearchProductListsResponseTests()
        {
            // TODO uncomment below to create an instance of ProductlistSearchProductListsResponse
            //instance = new ProductlistSearchProductListsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistSearchProductListsResponse
        /// </summary>
        [Fact]
        public void ProductlistSearchProductListsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistSearchProductListsResponse
            //Assert.IsType<ProductlistSearchProductListsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

        /// <summary>
        /// Test the property 'TotalSize'
        /// </summary>
        [Fact]
        public void TotalSizeTest()
        {
            // TODO unit test for the property 'TotalSize'
        }
    }
}
