/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product-list.Model;
using product-list.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product-list.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistListProductListsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistListProductListsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistListProductListsResponse
        //private ProductlistListProductListsResponse instance;

        public ProductlistListProductListsResponseTests()
        {
            // TODO uncomment below to create an instance of ProductlistListProductListsResponse
            //instance = new ProductlistListProductListsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistListProductListsResponse
        /// </summary>
        [Fact]
        public void ProductlistListProductListsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistListProductListsResponse
            //Assert.IsType<ProductlistListProductListsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Lists'
        /// </summary>
        [Fact]
        public void ListsTest()
        {
            // TODO unit test for the property 'Lists'
        }

        /// <summary>
        /// Test the property 'NextPageToken'
        /// </summary>
        [Fact]
        public void NextPageTokenTest()
        {
            // TODO unit test for the property 'NextPageToken'
        }
    }
}
