/*
 * Collection Service
 *
 * API for managing collection
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product-list.Model;
using product-list.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product-list.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistDeleteProductListAssociationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistDeleteProductListAssociationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistDeleteProductListAssociationRequest
        //private ProductlistDeleteProductListAssociationRequest instance;

        public ProductlistDeleteProductListAssociationRequestTests()
        {
            // TODO uncomment below to create an instance of ProductlistDeleteProductListAssociationRequest
            //instance = new ProductlistDeleteProductListAssociationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistDeleteProductListAssociationRequest
        /// </summary>
        [Fact]
        public void ProductlistDeleteProductListAssociationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistDeleteProductListAssociationRequest
            //Assert.IsType<ProductlistDeleteProductListAssociationRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
