/*
 * Collection Service
 *
 * API for managing collection
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product-list.Model;
using product-list.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product-list.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistProductListError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistProductListErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistProductListError
        //private ProductlistProductListError instance;

        public ProductlistProductListErrorTests()
        {
            // TODO uncomment below to create an instance of ProductlistProductListError
            //instance = new ProductlistProductListError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistProductListError
        /// </summary>
        [Fact]
        public void ProductlistProductListErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistProductListError
            //Assert.IsType<ProductlistProductListError>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
