/*
 * Collection Service
 *
 * API for managing collection
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product-list.Model;
using product-list.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product-list.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistOrderBy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistOrderByTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistOrderBy
        //private ProductlistOrderBy instance;

        public ProductlistOrderByTests()
        {
            // TODO uncomment below to create an instance of ProductlistOrderBy
            //instance = new ProductlistOrderBy();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistOrderBy
        /// </summary>
        [Fact]
        public void ProductlistOrderByInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistOrderBy
            //Assert.IsType<ProductlistOrderBy>(instance);
        }

        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }

        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Fact]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }
    }
}
