/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product-list.Model;
using product-list.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product-list.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistGetProductListsCountRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistGetProductListsCountRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistGetProductListsCountRequest
        //private ProductlistGetProductListsCountRequest instance;

        public ProductlistGetProductListsCountRequestTests()
        {
            // TODO uncomment below to create an instance of ProductlistGetProductListsCountRequest
            //instance = new ProductlistGetProductListsCountRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistGetProductListsCountRequest
        /// </summary>
        [Fact]
        public void ProductlistGetProductListsCountRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistGetProductListsCountRequest
            //Assert.IsType<ProductlistGetProductListsCountRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
    }
}
