/*
 * Collection Service
 *
 * API for managing collection
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product-list.Model;
using product-list.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product-list.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistGetProductListByUrlKeyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistGetProductListByUrlKeyRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistGetProductListByUrlKeyRequest
        //private ProductlistGetProductListByUrlKeyRequest instance;

        public ProductlistGetProductListByUrlKeyRequestTests()
        {
            // TODO uncomment below to create an instance of ProductlistGetProductListByUrlKeyRequest
            //instance = new ProductlistGetProductListByUrlKeyRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistGetProductListByUrlKeyRequest
        /// </summary>
        [Fact]
        public void ProductlistGetProductListByUrlKeyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistGetProductListByUrlKeyRequest
            //Assert.IsType<ProductlistGetProductListByUrlKeyRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'UrlKey'
        /// </summary>
        [Fact]
        public void UrlKeyTest()
        {
            // TODO unit test for the property 'UrlKey'
        }

        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Fact]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }
    }
}
