/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product-list.Model;
using product-list.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product-list.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistBulkUpdateProductListAssociationsRequestProductListAssociationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation
        //private ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation instance;

        public ProductlistBulkUpdateProductListAssociationsRequestProductListAssociationTests()
        {
            // TODO uncomment below to create an instance of ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation
            //instance = new ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation
        /// </summary>
        [Fact]
        public void ProductlistBulkUpdateProductListAssociationsRequestProductListAssociationInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation
            //Assert.IsType<ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
    }
}
