/*
 * Collection Service
 *
 * API for managing collection
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product-list.Model;
using product-list.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product-list.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistCreateProductListRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistCreateProductListRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistCreateProductListRequest
        //private ProductlistCreateProductListRequest instance;

        public ProductlistCreateProductListRequestTests()
        {
            // TODO uncomment below to create an instance of ProductlistCreateProductListRequest
            //instance = new ProductlistCreateProductListRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistCreateProductListRequest
        /// </summary>
        [Fact]
        public void ProductlistCreateProductListRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistCreateProductListRequest
            //Assert.IsType<ProductlistCreateProductListRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'UrlKey'
        /// </summary>
        [Fact]
        public void UrlKeyTest()
        {
            // TODO unit test for the property 'UrlKey'
        }

        /// <summary>
        /// Test the property 'EntityType'
        /// </summary>
        [Fact]
        public void EntityTypeTest()
        {
            // TODO unit test for the property 'EntityType'
        }

        /// <summary>
        /// Test the property 'EntityCode'
        /// </summary>
        [Fact]
        public void EntityCodeTest()
        {
            // TODO unit test for the property 'EntityCode'
        }

        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
    }
}
