/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product-list.Model;
using product-list.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product-list.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistUpdateProductListRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistUpdateProductListRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistUpdateProductListRequest
        //private ProductlistUpdateProductListRequest instance;

        public ProductlistUpdateProductListRequestTests()
        {
            // TODO uncomment below to create an instance of ProductlistUpdateProductListRequest
            //instance = new ProductlistUpdateProductListRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistUpdateProductListRequest
        /// </summary>
        [Fact]
        public void ProductlistUpdateProductListRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistUpdateProductListRequest
            //Assert.IsType<ProductlistUpdateProductListRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'UrlKey'
        /// </summary>
        [Fact]
        public void UrlKeyTest()
        {
            // TODO unit test for the property 'UrlKey'
        }

        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }

        /// <summary>
        /// Test the property 'AttributesMask'
        /// </summary>
        [Fact]
        public void AttributesMaskTest()
        {
            // TODO unit test for the property 'AttributesMask'
        }
    }
}
