/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product-list.Model;
using product-list.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product-list.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistSearchProductListsByIdsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistSearchProductListsByIdsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistSearchProductListsByIdsRequest
        //private ProductlistSearchProductListsByIdsRequest instance;

        public ProductlistSearchProductListsByIdsRequestTests()
        {
            // TODO uncomment below to create an instance of ProductlistSearchProductListsByIdsRequest
            //instance = new ProductlistSearchProductListsByIdsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistSearchProductListsByIdsRequest
        /// </summary>
        [Fact]
        public void ProductlistSearchProductListsByIdsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistSearchProductListsByIdsRequest
            //Assert.IsType<ProductlistSearchProductListsByIdsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Ids'
        /// </summary>
        [Fact]
        public void IdsTest()
        {
            // TODO unit test for the property 'Ids'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Fact]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }
    }
}
