/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product-list.Model;
using product-list.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product-list.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistGetProductListByCodeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistGetProductListByCodeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistGetProductListByCodeRequest
        //private ProductlistGetProductListByCodeRequest instance;

        public ProductlistGetProductListByCodeRequestTests()
        {
            // TODO uncomment below to create an instance of ProductlistGetProductListByCodeRequest
            //instance = new ProductlistGetProductListByCodeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistGetProductListByCodeRequest
        /// </summary>
        [Fact]
        public void ProductlistGetProductListByCodeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistGetProductListByCodeRequest
            //Assert.IsType<ProductlistGetProductListByCodeRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
    }
}
