/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product-list.Model;
using product-list.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product-list.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistGetProductListByUrlKeyResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistGetProductListByUrlKeyResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistGetProductListByUrlKeyResponse
        //private ProductlistGetProductListByUrlKeyResponse instance;

        public ProductlistGetProductListByUrlKeyResponseTests()
        {
            // TODO uncomment below to create an instance of ProductlistGetProductListByUrlKeyResponse
            //instance = new ProductlistGetProductListByUrlKeyResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistGetProductListByUrlKeyResponse
        /// </summary>
        [Fact]
        public void ProductlistGetProductListByUrlKeyResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistGetProductListByUrlKeyResponse
            //Assert.IsType<ProductlistGetProductListByUrlKeyResponse>(instance);
        }

        /// <summary>
        /// Test the property 'List'
        /// </summary>
        [Fact]
        public void ListTest()
        {
            // TODO unit test for the property 'List'
        }
    }
}
