/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product-list.Model;
using product-list.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product-list.Test.Model
{
    /// <summary>
    ///  Class for testing SearchProductListsRequestQuery
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchProductListsRequestQueryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchProductListsRequestQuery
        //private SearchProductListsRequestQuery instance;

        public SearchProductListsRequestQueryTests()
        {
            // TODO uncomment below to create an instance of SearchProductListsRequestQuery
            //instance = new SearchProductListsRequestQuery();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchProductListsRequestQuery
        /// </summary>
        [Fact]
        public void SearchProductListsRequestQueryInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchProductListsRequestQuery
            //Assert.IsType<SearchProductListsRequestQuery>(instance);
        }

        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
