/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product-list.Model;
using product-list.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product-list.Test.Model
{
    /// <summary>
    ///  Class for testing SetProductListAssociationsRequestAssociation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetProductListAssociationsRequestAssociationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SetProductListAssociationsRequestAssociation
        //private SetProductListAssociationsRequestAssociation instance;

        public SetProductListAssociationsRequestAssociationTests()
        {
            // TODO uncomment below to create an instance of SetProductListAssociationsRequestAssociation
            //instance = new SetProductListAssociationsRequestAssociation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SetProductListAssociationsRequestAssociation
        /// </summary>
        [Fact]
        public void SetProductListAssociationsRequestAssociationInstanceTest()
        {
            // TODO uncomment below to test "IsType" SetProductListAssociationsRequestAssociation
            //Assert.IsType<SetProductListAssociationsRequestAssociation>(instance);
        }

        /// <summary>
        /// Test the property 'ListId'
        /// </summary>
        [Fact]
        public void ListIdTest()
        {
            // TODO unit test for the property 'ListId'
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }

        /// <summary>
        /// Test the property 'ProductGrn'
        /// </summary>
        [Fact]
        public void ProductGrnTest()
        {
            // TODO unit test for the property 'ProductGrn'
        }
    }
}
