/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using productlist.Model;
using productlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace productlist.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistProductListAssociation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistProductListAssociationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistProductListAssociation
        //private ProductlistProductListAssociation instance;

        public ProductlistProductListAssociationTests()
        {
            // TODO uncomment below to create an instance of ProductlistProductListAssociation
            //instance = new ProductlistProductListAssociation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistProductListAssociation
        /// </summary>
        [Fact]
        public void ProductlistProductListAssociationInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistProductListAssociation
            //Assert.IsType<ProductlistProductListAssociation>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'ListId'
        /// </summary>
        [Fact]
        public void ListIdTest()
        {
            // TODO unit test for the property 'ListId'
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }

        /// <summary>
        /// Test the property 'ProductGrn'
        /// </summary>
        [Fact]
        public void ProductGrnTest()
        {
            // TODO unit test for the property 'ProductGrn'
        }
    }
}
