/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using productlist.Model;
using productlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace productlist.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistGetProductListsCountResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistGetProductListsCountResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistGetProductListsCountResponse
        //private ProductlistGetProductListsCountResponse instance;

        public ProductlistGetProductListsCountResponseTests()
        {
            // TODO uncomment below to create an instance of ProductlistGetProductListsCountResponse
            //instance = new ProductlistGetProductListsCountResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistGetProductListsCountResponse
        /// </summary>
        [Fact]
        public void ProductlistGetProductListsCountResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistGetProductListsCountResponse
            //Assert.IsType<ProductlistGetProductListsCountResponse>(instance);
        }

        /// <summary>
        /// Test the property 'TotalSize'
        /// </summary>
        [Fact]
        public void TotalSizeTest()
        {
            // TODO unit test for the property 'TotalSize'
        }
    }
}
