/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using productlist.Model;
using productlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace productlist.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistBulkUpdateProductListAssociationsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistBulkUpdateProductListAssociationsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistBulkUpdateProductListAssociationsRequest
        //private ProductlistBulkUpdateProductListAssociationsRequest instance;

        public ProductlistBulkUpdateProductListAssociationsRequestTests()
        {
            // TODO uncomment below to create an instance of ProductlistBulkUpdateProductListAssociationsRequest
            //instance = new ProductlistBulkUpdateProductListAssociationsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistBulkUpdateProductListAssociationsRequest
        /// </summary>
        [Fact]
        public void ProductlistBulkUpdateProductListAssociationsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistBulkUpdateProductListAssociationsRequest
            //Assert.IsType<ProductlistBulkUpdateProductListAssociationsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'ProductListAssociations'
        /// </summary>
        [Fact]
        public void ProductListAssociationsTest()
        {
            // TODO unit test for the property 'ProductListAssociations'
        }
    }
}
