/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using productlist.Model;
using productlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace productlist.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistDeleteProductListAssociationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistDeleteProductListAssociationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistDeleteProductListAssociationResponse
        //private ProductlistDeleteProductListAssociationResponse instance;

        public ProductlistDeleteProductListAssociationResponseTests()
        {
            // TODO uncomment below to create an instance of ProductlistDeleteProductListAssociationResponse
            //instance = new ProductlistDeleteProductListAssociationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistDeleteProductListAssociationResponse
        /// </summary>
        [Fact]
        public void ProductlistDeleteProductListAssociationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistDeleteProductListAssociationResponse
            //Assert.IsType<ProductlistDeleteProductListAssociationResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Association'
        /// </summary>
        [Fact]
        public void AssociationTest()
        {
            // TODO unit test for the property 'Association'
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
    }
}
