/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using productlist.Model;
using productlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace productlist.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistGetProductListByIdRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistGetProductListByIdRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistGetProductListByIdRequest
        //private ProductlistGetProductListByIdRequest instance;

        public ProductlistGetProductListByIdRequestTests()
        {
            // TODO uncomment below to create an instance of ProductlistGetProductListByIdRequest
            //instance = new ProductlistGetProductListByIdRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistGetProductListByIdRequest
        /// </summary>
        [Fact]
        public void ProductlistGetProductListByIdRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistGetProductListByIdRequest
            //Assert.IsType<ProductlistGetProductListByIdRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
