/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using productlist.Model;
using productlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace productlist.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistSetProductListAssociationsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistSetProductListAssociationsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistSetProductListAssociationsRequest
        //private ProductlistSetProductListAssociationsRequest instance;

        public ProductlistSetProductListAssociationsRequestTests()
        {
            // TODO uncomment below to create an instance of ProductlistSetProductListAssociationsRequest
            //instance = new ProductlistSetProductListAssociationsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistSetProductListAssociationsRequest
        /// </summary>
        [Fact]
        public void ProductlistSetProductListAssociationsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistSetProductListAssociationsRequest
            //Assert.IsType<ProductlistSetProductListAssociationsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'ListId'
        /// </summary>
        [Fact]
        public void ListIdTest()
        {
            // TODO unit test for the property 'ListId'
        }

        /// <summary>
        /// Test the property 'ProductGrn'
        /// </summary>
        [Fact]
        public void ProductGrnTest()
        {
            // TODO unit test for the property 'ProductGrn'
        }

        /// <summary>
        /// Test the property 'Associations'
        /// </summary>
        [Fact]
        public void AssociationsTest()
        {
            // TODO unit test for the property 'Associations'
        }
    }
}
