/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using productlist.Model;
using productlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace productlist.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistGetProductListAssociationsByProductGrnRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistGetProductListAssociationsByProductGrnRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistGetProductListAssociationsByProductGrnRequest
        //private ProductlistGetProductListAssociationsByProductGrnRequest instance;

        public ProductlistGetProductListAssociationsByProductGrnRequestTests()
        {
            // TODO uncomment below to create an instance of ProductlistGetProductListAssociationsByProductGrnRequest
            //instance = new ProductlistGetProductListAssociationsByProductGrnRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistGetProductListAssociationsByProductGrnRequest
        /// </summary>
        [Fact]
        public void ProductlistGetProductListAssociationsByProductGrnRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistGetProductListAssociationsByProductGrnRequest
            //Assert.IsType<ProductlistGetProductListAssociationsByProductGrnRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'ProductGrn'
        /// </summary>
        [Fact]
        public void ProductGrnTest()
        {
            // TODO unit test for the property 'ProductGrn'
        }
    }
}
