/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using productlist.Model;
using productlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace productlist.Test.Model
{
    /// <summary>
    ///  Class for testing ProductlistCreateProductListAssociationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductlistCreateProductListAssociationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductlistCreateProductListAssociationResponse
        //private ProductlistCreateProductListAssociationResponse instance;

        public ProductlistCreateProductListAssociationResponseTests()
        {
            // TODO uncomment below to create an instance of ProductlistCreateProductListAssociationResponse
            //instance = new ProductlistCreateProductListAssociationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductlistCreateProductListAssociationResponse
        /// </summary>
        [Fact]
        public void ProductlistCreateProductListAssociationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductlistCreateProductListAssociationResponse
            //Assert.IsType<ProductlistCreateProductListAssociationResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Association'
        /// </summary>
        [Fact]
        public void AssociationTest()
        {
            // TODO unit test for the property 'Association'
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
    }
}
