/*
 * Collection Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using product-list.Client;
using product-list.Api;
// uncomment below to import models
//using product-list.Model;

namespace product-list.Test.Api
{
    /// <summary>
    ///  Class for testing ProductListApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProductListApiTests : IDisposable
    {
        private ProductListApi instance;

        public ProductListApiTests()
        {
            instance = new ProductListApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductListApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ProductListApi
            //Assert.IsType<ProductListApi>(instance);
        }

        /// <summary>
        /// Test CreateProductList
        /// </summary>
        [Fact]
        public void CreateProductListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductlistCreateProductListRequest body = null;
            //var response = instance.CreateProductList(body);
            //Assert.IsType<ProductlistCreateProductListResponse>(response);
        }

        /// <summary>
        /// Test CreateProductListAssociation
        /// </summary>
        [Fact]
        public void CreateProductListAssociationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductlistCreateProductListAssociationRequest body = null;
            //var response = instance.CreateProductListAssociation(body);
            //Assert.IsType<ProductlistCreateProductListAssociationResponse>(response);
        }

        /// <summary>
        /// Test DeleteProductList
        /// </summary>
        [Fact]
        public void DeleteProductListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductlistDeleteProductListRequest body = null;
            //var response = instance.DeleteProductList(body);
            //Assert.IsType<ProductlistDeleteProductListResponse>(response);
        }

        /// <summary>
        /// Test DeleteProductListAssociation
        /// </summary>
        [Fact]
        public void DeleteProductListAssociationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductlistDeleteProductListAssociationRequest body = null;
            //var response = instance.DeleteProductListAssociation(body);
            //Assert.IsType<ProductlistDeleteProductListAssociationResponse>(response);
        }

        /// <summary>
        /// Test GetProductListAssociationsByProductGrn
        /// </summary>
        [Fact]
        public void GetProductListAssociationsByProductGrnTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductlistGetProductListAssociationsByProductGrnRequest body = null;
            //var response = instance.GetProductListAssociationsByProductGrn(body);
            //Assert.IsType<ProductlistGetProductListAssociationsByProductGrnResponse>(response);
        }

        /// <summary>
        /// Test GetProductListByCode
        /// </summary>
        [Fact]
        public void GetProductListByCodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductlistGetProductListByCodeRequest body = null;
            //var response = instance.GetProductListByCode(body);
            //Assert.IsType<ProductlistGetProductListByCodeResponse>(response);
        }

        /// <summary>
        /// Test GetProductListById
        /// </summary>
        [Fact]
        public void GetProductListByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductlistGetProductListByIdRequest body = null;
            //var response = instance.GetProductListById(body);
            //Assert.IsType<ProductlistGetProductListByIdResponse>(response);
        }

        /// <summary>
        /// Test GetProductListByUrlKey
        /// </summary>
        [Fact]
        public void GetProductListByUrlKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductlistGetProductListByUrlKeyRequest body = null;
            //var response = instance.GetProductListByUrlKey(body);
            //Assert.IsType<ProductlistGetProductListByUrlKeyResponse>(response);
        }

        /// <summary>
        /// Test GetProductListsCount
        /// </summary>
        [Fact]
        public void GetProductListsCountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductlistGetProductListsCountRequest body = null;
            //var response = instance.GetProductListsCount(body);
            //Assert.IsType<ProductlistGetProductListsCountResponse>(response);
        }

        /// <summary>
        /// Test ListProductListAssociations
        /// </summary>
        [Fact]
        public void ListProductListAssociationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductlistListProductListAssociationsRequest body = null;
            //var response = instance.ListProductListAssociations(body);
            //Assert.IsType<ProductlistListProductListAssociationsResponse>(response);
        }

        /// <summary>
        /// Test ListProductLists
        /// </summary>
        [Fact]
        public void ListProductListsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductlistListProductListsRequest body = null;
            //var response = instance.ListProductLists(body);
            //Assert.IsType<ProductlistListProductListsResponse>(response);
        }

        /// <summary>
        /// Test ProductListBulkUpdateProductListAssociations
        /// </summary>
        [Fact]
        public void ProductListBulkUpdateProductListAssociationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductlistBulkUpdateProductListAssociationsRequest body = null;
            //var response = instance.ProductListBulkUpdateProductListAssociations(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test SearchProductLists
        /// </summary>
        [Fact]
        public void SearchProductListsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductlistSearchProductListsRequest body = null;
            //var response = instance.SearchProductLists(body);
            //Assert.IsType<ProductlistSearchProductListsResponse>(response);
        }

        /// <summary>
        /// Test SearchProductListsByIds
        /// </summary>
        [Fact]
        public void SearchProductListsByIdsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductlistSearchProductListsByIdsRequest body = null;
            //var response = instance.SearchProductListsByIds(body);
            //Assert.IsType<ProductlistSearchProductListsByIdsResponse>(response);
        }

        /// <summary>
        /// Test SetProductListAssociations
        /// </summary>
        [Fact]
        public void SetProductListAssociationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductlistSetProductListAssociationsRequest body = null;
            //var response = instance.SetProductListAssociations(body);
            //Assert.IsType<ProductlistSetProductListAssociationsResponse>(response);
        }

        /// <summary>
        /// Test UpdateProductList
        /// </summary>
        [Fact]
        public void UpdateProductListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductlistUpdateProductListRequest body = null;
            //var response = instance.UpdateProductList(body);
            //Assert.IsType<ProductlistUpdateProductListResponse>(response);
        }
    }
}
